# Generated by Django 3.2 on 2023-08-13 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('Gundog', 'Gundog'), ('Hound', 'Hound'), ('Pastoral', 'Pastoral'), ('Terrier', 'Terrier'), ('Toy', 'Toy'), ('Utility', 'Utility'), ('Working', 'Working')], max_length=16)),
                ('breed', models.CharField(max_length=32)),
                ('size', models.CharField(choices=[('XS', 'x-small'), ('S', 'small'), ('M', 'medium'), ('L', 'large'), ('XL', 'x-large')], max_length=5)),
                ('lifespan', models.IntegerField()),
                ('exercise_needs', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('grooming_needs', models.IntegerField()),
                ('intelligence', models.IntegerField()),
            ],
        ),
    ]
